[2022-12-27T04:33:23.154+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:33:09.481819+00:00 [queued]>
[2022-12-27T04:33:23.398+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:33:09.481819+00:00 [queued]>
[2022-12-27T04:33:23.402+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:33:23.406+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-27T04:33:23.410+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:33:23.540+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 04:33:09.481819+00:00
[2022-12-27T04:33:23.624+0000] {standard_task_runner.py:55} INFO - Started process 616 to run task
[2022-12-27T04:33:23.682+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T04:33:09.481819+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpfc__y8k6']
[2022-12-27T04:33:23.692+0000] {standard_task_runner.py:83} INFO - Job 365: Subtask extract_test
[2022-12-27T04:33:24.645+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:33:09.481819+00:00 [running]> on host 6026fe33842a
[2022-12-27T04:33:26.454+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:33:09.481819+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T04:33:09.481819+00:00
[2022-12-27T04:33:26.496+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: connecting to broker:9092 [('172.25.0.4', 9092) IPv4]
[2022-12-27T04:33:26.513+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:33:26.535+0000] {conn.py:401} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: Connection complete.
[2022-12-27T04:33:26.732+0000] {conn.py:1106} INFO - Broker version identifed as 1.0.0
[2022-12-27T04:33:26.734+0000] {conn.py:1108} INFO - Set configuration api_version=(1, 0, 0) to skip auto check_version requests on startup
[2022-12-27T04:33:26.773+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('projek_akhir',)
[2022-12-27T04:33:30.819+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-27T04:33:30.828+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-27T04:34:31.629+0000] {logging_mixin.py:137} INFO - Connected
[2022-12-27T04:34:31.691+0000] {streaming.py:185} INFO - Stream connected
[2022-12-27T04:34:35.188+0000] {logging_mixin.py:137} INFO - b'{"text": "Day 27: A drama that deserves a shout out\\n\\nALICE IN BORDERLAND\\n\\naaashhhhhshhshshsjzjzjzj really thankful they released the season 2 this year \\ud83e\\udd79 this was such a perfect way to end the series, but I hope they release special episodes \\ud83e\\udd79 I love this drama so much \\ud83e\\udef6\\ud83c\\udffb\\ud83e\\udef6\\ud83c\\udffb https://t.co/67Hwe2qiLt"}'
[2022-12-27T04:34:35.270+0000] {conn.py:372} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: connecting to broker:9092 [('172.25.0.4', 9092) IPv4]
[2022-12-27T04:34:35.287+0000] {conn.py:401} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: Connection complete.
[2022-12-27T04:34:35.299+0000] {conn.py:811} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.25.0.4', 9092)]>: Closing connection. 
[2022-12-27T04:34:39.214+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-12-27T04:34:39.246+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 616. PIDs of all processes in the group: [616]
[2022-12-27T04:34:39.256+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 616
[2022-12-27T04:34:39.304+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-27T04:34:39.340+0000] {streaming.py:203} ERROR - Stream encountered an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/streaming.py", line 91, in _connect
    chunk_size=self.chunk_size
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 866, in iter_lines
    chunk_size=chunk_size, decode_unicode=decode_unicode
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py", line 758, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-27T04:34:39.418+0000] {logging_mixin.py:137} INFO - Disconnected
[2022-12-27T04:34:39.423+0000] {streaming.py:193} INFO - Stream disconnected
[2022-12-27T04:34:39.436+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: connecting to broker:9092 [('172.25.0.4', 9092) IPv4]
[2022-12-27T04:34:39.541+0000] {conn.py:401} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: Connection complete.
[2022-12-27T04:34:39.665+0000] {cluster.py:376} INFO - Group coordinator for consumers is (1003, 'broker', 9092, None)
[2022-12-27T04:34:39.667+0000] {base.py:688} INFO - Discovered coordinator 1003 for group consumers
[2022-12-27T04:34:39.670+0000] {base.py:735} INFO - Starting new heartbeat thread
[2022-12-27T04:34:39.675+0000] {consumer.py:342} INFO - Revoking previously assigned partitions () for group consumers
[2022-12-27T04:34:39.680+0000] {conn.py:372} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: connecting to broker:9092 [('172.25.0.4', 9092) IPv4]
[2022-12-27T04:34:39.784+0000] {conn.py:401} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: Connection complete.
[2022-12-27T04:34:39.786+0000] {conn.py:811} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.25.0.4', 9092)]>: Closing connection. 
[2022-12-27T04:34:39.893+0000] {base.py:447} INFO - (Re-)joining group consumers
[2022-12-27T04:34:39.954+0000] {base.py:516} INFO - Elected group leader -- performing partition assignments using range
[2022-12-27T04:34:40.019+0000] {base.py:333} INFO - Successfully joined group consumers with generation 1
[2022-12-27T04:34:40.025+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('projek_akhir', 0)]
[2022-12-27T04:34:40.031+0000] {consumer.py:239} INFO - Setting newly assigned partitions (('projek_akhir', 0),) for group consumers
[2022-12-27T04:34:40.280+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 106, in start_etl
    load(msg.value)
  File "/opt/airflow/dags/etl.py", line 94, in load
    temp = json.loads(msg)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not ConsumerRecord
[2022-12-27T04:34:40.383+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T043309, start_date=20221227T043323, end_date=20221227T043440
[2022-12-27T04:34:40.515+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 365 for task extract_test (the JSON object must be str, bytes or bytearray, not ConsumerRecord; 616)
[2022-12-27T04:34:40.662+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=616, status='terminated', exitcode=1, started='04:33:22') (616) terminated with exit code 1
