[2022-12-27T00:05:03.990+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2022-12-27T00:05:04.002+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2022-12-27T00:05:04.003+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T00:05:04.004+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2022-12-27T00:05:04.004+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T00:05:04.017+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-26 00:00:00+00:00
[2022-12-27T00:05:04.027+0000] {standard_task_runner.py:55} INFO - Started process 2602 to run task
[2022-12-27T00:05:04.030+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmph_vrgi_b']
[2022-12-27T00:05:04.033+0000] {standard_task_runner.py:83} INFO - Job 150: Subtask extract_test
[2022-12-27T00:05:04.462+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test scheduled__2022-12-26T00:00:00+00:00 [running]> on host 3dc0e72111ec
[2022-12-27T00:05:04.660+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2022-12-27T00:05:04.673+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T00:05:04.676+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T00:05:04.678+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T00:05:04.684+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T00:05:04.685+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T00:05:04.687+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 14, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-27T00:05:04.726+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221226T000000, start_date=20221227T000503, end_date=20221227T000504
[2022-12-27T00:05:04.752+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 150 for task extract_test (NoBrokersAvailable; 2602)
[2022-12-27T00:05:04.809+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T00:05:04.869+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
