[2022-12-27T04:19:39.589+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:18:25.039586+00:00 [queued]>
[2022-12-27T04:19:40.083+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:18:25.039586+00:00 [queued]>
[2022-12-27T04:19:40.088+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:19:40.091+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-27T04:19:40.094+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:19:40.441+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 04:18:25.039586+00:00
[2022-12-27T04:19:40.601+0000] {standard_task_runner.py:55} INFO - Started process 548 to run task
[2022-12-27T04:19:40.768+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T04:18:25.039586+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpuyc45_r8']
[2022-12-27T04:19:40.928+0000] {standard_task_runner.py:83} INFO - Job 328: Subtask extract_test
[2022-12-27T04:19:46.185+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:18:25.039586+00:00 [running]> on host 6026fe33842a
[2022-12-27T04:19:49.046+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:18:25.039586+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T04:18:25.039586+00:00
[2022-12-27T04:19:49.391+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.399+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.408+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:19:49.467+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.490+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.512+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.517+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.520+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:19:49.531+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.538+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.573+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.584+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.591+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:19:49.616+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.621+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.653+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.674+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.690+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:19:49.703+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.707+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.721+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.727+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.732+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:19:49.748+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.758+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.772+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.775+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.780+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:19:49.796+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:19:49.805+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:19:49.809+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 15, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-27T04:19:50.672+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T041825, start_date=20221227T041939, end_date=20221227T041950
[2022-12-27T04:19:51.191+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 328 for task extract_test (NoBrokersAvailable; 548)
[2022-12-27T04:19:53.342+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T04:19:54.932+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
