[2022-12-26T20:16:17.778+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T20:05:58.789377+00:00 [queued]>
[2022-12-26T20:16:17.981+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T20:05:58.789377+00:00 [queued]>
[2022-12-26T20:16:17.996+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T20:16:18.000+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-26T20:16:18.002+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T20:16:25.642+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-26 20:05:58.789377+00:00
[2022-12-26T20:16:28.297+0000] {standard_task_runner.py:55} INFO - Started process 123 to run task
[2022-12-26T20:16:28.685+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-26T20:05:58.789377+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpnrlxw9k9']
[2022-12-26T20:16:29.211+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask extract_test
[2022-12-26T20:17:59.228+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-26T20:05:58.789377+00:00 [running]> on host 90c4bc40493a
[2022-12-26T20:18:06.327+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T20:05:58.789377+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-26T20:05:58.789377+00:00
[2022-12-26T20:18:06.683+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:06.693+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:06.704+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-26T20:18:06.819+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:06.824+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:06.842+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:06.847+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:06.853+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-26T20:18:06.890+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:06.896+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:06.906+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:06.908+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:06.923+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-26T20:18:07.122+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:07.454+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:07.688+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:07.878+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:08.231+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-26T20:18:08.443+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T20:18:08.545+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T20:18:08.671+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 12, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker:9092'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 892, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-26T20:18:22.115+0000] {local_task_job.py:159} INFO - Task exited with return code Negsignal.SIGKILL
